"import React from 'react';\nimport { X, Calendar, User, Target } from 'lucide-react';\nimport { useUI } from '../../context/UIContext';\nimport { useAppState } from '../../context/AppStateContext';\nimport { getSettingBadge } from '../../utils/uiUtils';\n\nexport default function UnscheduledProjectsDrawer() {\n  const { isDrawerOpen, closeDrawer, openDrawer, activeDrawers } = useUI();\n  const { projects, settings } = useAppState();\n  \n  const isOpen = isDrawerOpen('unscheduledProjects');\n\n  // Unscheduled projects are those without a releaseDateVal AND with status \"Onboarding\"\n  const unscheduledProjects = projects\n    .filter(p => p.projectStatus === 'Onboarding' && (!p.releaseDateVal || p.releaseDateVal === 0))\n    .sort((a, b) => (a.name || '').localeCompare(b.name || ''));\n\n  const handleProjectClick = (projectId: string) => {\n    openDrawer('project', projectId);\n  };\n\n  if (!isOpen) return null;\n\n  const drawerIndex = activeDrawers.findIndex(d => d.type === 'unscheduledProjects');\n  const zIndexOverlay = 100 + (Math.max(0, drawerIndex) * 20);\n  const zIndexDrawer = 110 + (Math.max(0, drawerIndex) * 20);\n\n  return (\n    <>\n      {/* Overlay */}\n      <div \n        className={`fixed inset-0 bg-black/40 backdrop-blur-sm cursor-pointer animate-in fade-in duration-300`}\n        style={{ zIndex: zIndexOverlay }}\n        onClick={closeDrawer}\n      />\n\n      {/* Drawer */}\n      <div \n        className={`fixed top-0 right-0 h-full w-full max-w-md bg-white flex flex-col border-l border-border shadow-2xl animate-in slide-in-from-right duration-300`}\n        style={{ zIndex: zIndexDrawer }}\n      >\n        <div className=\"px-6 py-5 border-b border-border bg-slate-50 flex items-start justify-between shrink-0\">\n          <div className=\"min-w-0 pr-4\">\n             <h2 className=\"text-xl font-bold text-foreground tracking-tight truncate\">Unscheduled Projects</h2>\n             <p className=\"text-sm text-muted-foreground mt-1 truncate\">Projects missing a release date</p>\n  
<truncated 2849 bytes>
                    <div className="flex justify-between items-center pt-3 mt-3 border-t border-border gap-2 flex-wrap sm:flex-nowrap">
                      <div className="flex flex-col gap-1 items-start justify-center shrink-0">
                         {getSettingBadge('managers', p.assignee, settings)}
                      </div>
                      <div className="flex items-center gap-1.5 flex-wrap justify-end">
                          {getSettingBadge('phases', p.onboardingPhase || 'Not Started', settings)}
                      </div>
                    </div>