"import React, { useState, useEffect } from 'react';\nimport { updateProjectRecord } from '../../../api/dbService';\nimport { useAppState } from '../../../context/AppStateContext';\nimport { v4 as uuidv4 } from 'uuid';\nimport { Send, Activity, MessageSquare, User, ChevronDown, FileText } from 'lucide-react';\n\ninterface ProjectNotesTabProps {\n  project: any;\n}\n\nexport default function ProjectNotesTab({ project }: ProjectNotesTabProps) {\n  const { user } = useAppState();\n  const [newNote, setNewNote] = useState('');\n  const [isSaving, setIsSaving] = useState(false);\n  const [localNotes, setLocalNotes] = useState<any[]>([]);\n  const [isKycOpen, setIsKycOpen] = useState(false);\n\n  useEffect(() => {\n      setLocalNotes(project?.notes || []);\n  }, [project?.notes]);\n\n  const handleUpdate = async (field: string, value: any) => {\n    if (!project || project[field] === value) return;\n    try {\n      await updateProjectRecord({ ...project, [field]: value });\n    } catch (err) {\n      console.error(err);\n    }\n  };\n\n  const handleAddNote = async () => {\n    if (!newNote.trim() || !project) return;\n    \n    setIsSaving(true);\n    const noteObj = {\n      id: uuidv4(),\n      text: newNote.trim(),\n      timestamp: new Date().getTime(),\n      author: user?.name || 'Unknown User'\n    };\n\n    const currentNotes = project.notes || [];\n    const updatedNotes = [noteObj, ...currentNotes];\n\n    setLocalNotes(updatedNotes);\n    setNewNote('');\n\n    try {\n      await updateProjectRecord({ ...project, notes: updatedNotes });\n    } catch (err) {\n      console.error(err);\n      setLocalNotes(currentNotes);\n    } finally {\n      setIsSaving(false);\n    }\n  };\n\n  return (\n    <div className=\"flex flex-col h-full max-w-4xl mx-auto w-full\">\n           <div className=\"bg-white rounded-2xl shadow-sm border border-border mb-6 focus-within:ring-2 focus-within:ring-primary/20 focus-within:border-primary transition-all duration-300 flex flex-col\">\n               <textarea \n               
<truncated 5984 bytes>
                   placeholder="ANTIGRAVITY TEST..."

                       const timeString = isNaN(parsedDate.getTime()) ? 'Unknown Time' : parsedDate.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
  const [localNotes, setLocalNotes] = useState<any[]>([]);
      id: crypto.randomUUID(),
      await updateProjectRecord({ ...project, notes: updatedNotes }, {
        successMsg: `Note successfully added for '${project.name}'.`,
        errorMsg: `Failed to add note for '${project.name}'.`
      });