"import { test, expect } from '@playwright/test';\n\ntest.describe('Phase 4: Data Entry & Form Validation (Modals)', () => {\n  const timestamp = new Date().getTime();\n  const testClientName = `Test Client Phase 4 ${timestamp}`;\n  const testProjectName = `Test Project Phase 4 ${timestamp}`;\n  const testServiceName = `Test Service Phase 4 ${timestamp}`;\n\n  test.beforeEach(async ({ page }) => {\n    await page.goto('http://localhost:5173');\n    await page.waitForTimeout(1000); // Let data load\n  });\n\n  test('Add Client Modal Validation and Submission', async ({ page }) => {\n    // Open Add Client Modal\n    await page.getByText('Add New', { exact: true }).click({ force: true });\n    await page.waitForTimeout(300);\n    await page.getByText('Client', { exact: true }).last().click({ force: true });\n    \n    const modal = page.locator('.fixed.inset-0').last();\n    await expect(modal).toBeVisible();\n\n    // Form Validation: try submitting without required fields\n    await page.getByRole('button', { name: 'Create Client' }).click({ force: true });\n    // Assuming HTML5 validation prevents default, or we can check if modal is still open\n    await expect(modal).toBeVisible();\n\n    // Fill the required fields\n    await page.getByPlaceholder('Enter client name...').fill(testClientName);\n    \n    // Select Type\n    await page.getByText('Select Type').click({ force: true });\n    await page.locator('.absolute button').first().click({ force: true });\n\n    // Submit\n    await page.getByRole('button', { name: 'Create Client' }).click({ force: true });\n    \n    // Wait for modal to close\n    await expect(modal).toBeHidden({ timeout: 5000 });\n  });\n\n  test('Add Project Modal Validation and Submission', async ({ page }) => {\n    // Open Add Project Modal\n    await page.getByText('Add New', { exact: true }).click({ force: true });\n    await page.waitForTimeout(300);\n    await page.getByText('Project', { exact: true }).last().click({ force: true });\n    \n    const modal = page.locator('.fixed.i
<truncated 1409 bytes>
    const modal = page.getByRole('dialog').first();
    await expect(modal).toBeVisible();
    const modal = page.getByRole('dialog').first();
    await expect(modal).toBeVisible();
    const modal = page.getByRole('dialog').first();
    await expect(modal).toBeVisible();
"    // Open Add Client Modal\n    await page.getByText('Add New', { exact: true }).click({ force: true });\n    await page.waitForTimeout(300);\n    await page.getByText('Client', { exact: true }).last().click({ force: true });\n    \n    const modal = page.locator('.z-\\\\[130\\\\]').first();\n    await expect(modal).toBeVisible();\n\n    // Form Validation: try submitting without required fields\n    await page.getByRole('button', { name: 'Create Client' }).click({ force: true });\n    // Assuming HTML5 validation prevents default, or we can check if modal is still open\n    await expect(modal).toBeVisible();\n\n    // Fill the required fields\n    await page.getByPlaceholder('Enter client name...').fill(testClientName);\n    \n    // Select Type\n    await page.getByText('Select Type').click({ force: true });\n    await page.locator('.absolute button').first().click({ force: true });\n\n    // Submit\n    await page.getByRole('button', { name: 'Create Client' }).click({ force: true });\n    \n    // Wait for modal to close\n    await expect(modal).toBeHidden({ timeout: 5000 });\n  });\n\n  test('Add Project Modal Validation and Submission', async ({ page }) => {\n    // Open Add Project Modal\n    await page.getByText('Add New', { exact: true }).click({ force: true });\n    await page.waitForTimeout(300);\n    await page.getByText('Project', { exact: true }).last().click({ force: true });\n    \n    const modal = page.locator('.z-\\\\[130\\\\]').first();\n    await expect(modal).toBeVisible();\n\n    // Fill the required fields\n    await page.getByPlaceholder('Enter project name...').fill(testProjectName);\n    await page.locator('input[placeholder=\"0\"]').fill('100');\n\n    // Submit\n    await page.getByRole('button', { name: 'Create Project' }).click({ force: true });\n    \n    // Wait for modal to close\n    await expect(modal).toBeHidden({ timeout: 5000 });\n  });\n\n  test('Add Service Modal Validation and Submission', async ({ page }) => {\n    // Open Add Service Modal\n    await page.getByText('A
<truncated 279 bytes>