"import React, { useEffect, useState, useMemo } from 'react';\nimport { Line } from 'react-chartjs-2';\nimport { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Filler } from 'chart.js';\nimport { getHealthHistory } from '../../../api/dbService';\n\nChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Filler);\n\ninterface ClientTrendsTabProps {\n  client: any;\n}\n\nexport default function ClientTrendsTab({ client }: ClientTrendsTabProps) {\n    const [history, setHistory] = useState<any[]>([]);\n    const [loading, setLoading] = useState(true);\n    const [filter, setFilter] = useState<'30' | '90' | '365' | 'all'>('30');\n\n    useEffect(() => {\n        async function fetchH() {\n            setLoading(true);\n            try {\n                if (client?.clientId || client?.id) {\n                    const h = await getHealthHistory(client.clientId || client.id);\n                    setHistory(Array.isArray(h) ? h : []);\n                } else {\n                    setHistory([]);\n                }\n            } catch (e) {\n                console.error(e);\n            }\n            setLoading(false);\n        }\n        fetchH();\n    }, [client]);\n\n    const optimizedHistory = useMemo(() => {\n        if (!history || history.length === 0) return [];\n        \n        const now = new Date().getTime();\n        let cutoff = 0;\n        if (filter !== 'all') {\n            cutoff = now - (parseInt(filter) * 24 * 60 * 60 * 1000);\n        }\n        \n        const inWindow = history.filter(h => h.timeVal >= cutoff);\n        if (inWindow.length === 0) return [];\n\n        const chronological = [...inWindow].sort((a,b) => a.timeVal - b.timeVal);\n\n        const dailyMap = new Map<string, any>();\n        chronological.forEach(h => {\n            const dateStr = new Date(h.timeVal).toDateString();\n            dailyMap.set(dateStr, h);\n        });\n\n        const dailyArray = Array.from(dailyMap.values()).sort((a,b) => a.timeVal - b.ti
<truncated 9744 bytes>
"        <div className=\"flex flex-col\">\n            <div className=\"flex items-center justify-between mb-2\">\n               <h3 className=\"font-semibold text-foreground text-sm\">Client Health Trajectory</h3>\n               <div className=\"inline-flex items-center rounded-lg p-[3px] text-muted-foreground bg-slate-100 w-max justify-start flex-nowrap h-9 shrink-0\">\n                   <button onClick={() => setFilter('30')} className={`relative inline-flex h-full items-center justify-center gap-1.5 rounded-md px-3 py-1 text-[13px] font-medium whitespace-nowrap transition-all duration-200 active:scale-95 ${filter === '30' ? 'bg-white text-foreground shadow-sm' : 'hover:text-foreground'}`}>30D</button>\n                   <button onClick={() => setFilter('90')} className={`relative inline-flex h-full items-center justify-center gap-1.5 rounded-md px-3 py-1 text-[13px] font-medium whitespace-nowrap transition-all duration-200 active:scale-95 ${filter === '90' ? 'bg-white text-foreground shadow-sm' : 'hover:text-foreground'}`}>90D</button>\n                   <button onClick={() => setFilter('365')} className={`relative inline-flex h-full items-center justify-center gap-1.5 rounded-md px-3 py-1 text-[13px] font-medium whitespace-nowrap transition-all duration-200 active:scale-95 ${filter === '365' ? 'bg-white text-foreground shadow-sm' : 'hover:text-foreground'}`}>1Y</button>\n                   <button onClick={() => setFilter('all')} className={`relative inline-flex h-full items-center justify-center gap-1.5 rounded-md px-3 py-1 text-[13px] font-medium whitespace-nowrap transition-all duration-200 active:scale-95 ${filter === 'all' ? 'bg-white text-foreground shadow-sm' : 'hover:text-foreground'}`}>All</button>\n               </div>\n            </div>\n            \n            <div className=\"bg-white border border-border rounded-xl p-4 h-64 shadow-sm relative mb-6\">\n                <Line data={chartData} options={chartOptions as any} />\n            </div>\n            \n            <div className=\
<truncated 71 bytes>
            tooltip: {
                backgroundColor: 'rgba(255, 255, 255, 0.95)',
                titleColor: '#0f172a',
                bodyColor: '#334155',
                borderColor: '#e2e8f0',
                borderWidth: 1,
                padding: 12,
                displayColors: false,
                titleFont: { size: 13, weight: 'bold' },
                bodyFont: { size: 12 },
                callbacks: {
                    label: function(context: any) {
                        return `Health Score: ${context.parsed.y}`;
                    }
                }
            }