"import React, { useMemo } from 'react';\nimport { Briefcase } from 'lucide-react';\nimport { useAppState } from '../../../context/AppStateContext';\nimport { useUI } from '../../../context/UIContext';\nimport { getSafeHex, hexToRgba, renderIcon } from '../../../utils/uiUtils';\n\ninterface ProjectServicesTabProps {\n  project: any;\n}\n\nexport default function ProjectServicesTab({ project }: ProjectServicesTabProps) {\n    const { services, settings } = useAppState();\n    const { openDrawer, openModal } = useUI();\n\n    const projectServices = useMemo(() => {\n        return services.filter(s => {\n            const pId = project?.id || project?.projectId;\n            return s.projectId === pId || (Array.isArray(s.projectIds) && s.projectIds.includes(pId));\n        }).sort((a: any, b: any) => {\n            const valA = a.dateVal || 0;\n            const valB = b.dateVal || 0;\n            return valB - valA;\n        });\n    }, [services, project]);\n\n    const parseCurrency = (val: any) => {\n        if (typeof val === 'number') return val;\n        if (typeof val === 'string') {\n            const num = parseFloat(val.replace(/[^0-9.-]+/g,\"\"));\n            return isNaN(num) ? 0 : num;\n        }\n        return 0;\n    };\n\n    const formatCurrency = (val: any) => {\n        const num = parseCurrency(val);\n        return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(num);\n    };\n\n    return (\n        <div className=\"flex flex-col space-y-4\">\n            <div className=\"flex justify-between items-end mb-2\">\n                <div>\n                    <h3 className=\"font-semibold text-foreground text-sm\">Project Services</h3>\n                    <p className=\"text-xs text-muted-foreground mt-1\">All service history logged specifically to this project.</p>\n                </div>\n                <button \n                    onClick={() => openModal('addService')}\n                    className=\"inline-flex items-center justify-center gap-2 rounded-md te
<truncated 6331 bytes>
                                            {s.type === 'Additional' && (() => {
                                                const displayStatus = (s.outcome && s.outcome !== 'Pending') ? s.outcome : (s.status || s.outcome);
            <div className="flex justify-between items-end mb-2">
                <div>
                    <h3 className="font-semibold text-foreground text-sm">Project Services</h3>
                    <p className="text-xs text-muted-foreground mt-1">All service history logged specifically to this project.</p>
                </div>
            </div>
                                            <span className="text-xs text-slate-500 font-medium mt-0.5">{s.clientName || s.clients?.[0] || 'Unknown Client'}</span>